spring.application.name=gplsp
server.port=18085
spring.datasource.url=jdbc:mysql://localhost:3306/reactgpl?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.error.include-stacktrace=always
spring.jackson.serialization.fail-on-empty-beans=false